#!/bin/bash

if [[ ! -z "$DOKKU_DEV" ]]; then
  export DOKKU_DEV=true
  export DOKKU_ROOT=/home/dokku

  chmod +x commands
  chmod +x install
  chmod +x dockerfiles/bin/manage

  ./commands rabbitmq:stop

  docker rmi ohardy/rabbitmq
  rm -rf /home/dokku/.o_rabbitmq
  docker build --no-cache -t ohardy/rabbitmq dockerfiles/

  ./install
fi
